name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: vx.x.x

      - name: Test
        run: deno test -A
